# Generated by Django 2.0.4 on 2018-05-01 16:08

import curriculo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ra', models.CharField(max_length=7)),
                ('foto', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('curriculo.user',),
            managers=[
                ('objects', curriculo.models.ContasManager()),
            ],
        ),
    ]
