# Generated by Django 2.0.3 on 2018-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_disciplina_idcoordenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
