# Generated by Django 2.0.3 on 2018-05-01 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0005_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='idCoordenador',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='Coordenador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
