# Generated by Django 2.0.3 on 2018-05-01 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0006_auto_20180501_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DTInicioMatricula', models.DateField(blank=True, null=True)),
                ('DTFimMatricula', models.DateField(blank=True, null=True)),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('turma', models.CharField(max_length=1)),
                ('metodologia', models.TextField(null=True)),
                ('recursos', models.TextField(null=True)),
                ('criterioAvaliacao', models.TextField(null=True)),
                ('planoDeAulas', models.TextField(null=True)),
                ('idCoordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idCurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Curso')),
                ('idDisciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Disciplina')),
                ('idProfessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='idprofessor', to='curriculo.Professor')),
            ],
        ),
    ]
