# Generated by Django 2.0.3 on 2018-05-01 19:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0008_disciplina_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DTSolicitacao', models.DateTimeField(default=datetime.datetime(2018, 5, 1, 16, 26, 28, 705624))),
                ('status', models.CharField(default='Solicitada', max_length=10)),
                ('idAluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Aluno')),
                ('idCoordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='idCoordenador', to=settings.AUTH_USER_MODEL)),
                ('idDisciplinaOfertada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.DisciplinaOfertada')),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 16, 26, 28, 702624)),
        ),
    ]
