# Generated by Django 2.0.3 on 2018-05-01 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0010_auto_20180501_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.SlugField(max_length=6)),
                ('status', models.CharField(max_length=15)),
                ('DtInicioRespostas', models.DateField()),
                ('DtFimRespostas', models.DateField()),
                ('idAtividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Atividade')),
                ('idDisciplinaOfertada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.DisciplinaOfertada')),
                ('idProfessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Professor')),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 16, 39, 21, 368818)),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='DTSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 16, 39, 21, 371818)),
        ),
    ]
