# Generated by Django 2.0.3 on 2018-05-01 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0011_auto_20180501_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=60)),
                ('Reposta', models.TextField()),
                ('DtEntrega', models.DateTimeField(default=datetime.datetime(2018, 5, 1, 17, 12, 50, 311605))),
                ('StatusEntrega', models.CharField(default='Entregue', max_length=9)),
                ('Nota', models.DecimalField(decimal_places=0, max_digits=3)),
                ('DtAvaliacao', models.DateField()),
                ('Obs', models.TextField(blank=True, null=True)),
                ('idAluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Aluno')),
                ('idAtividadeVinculada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.AtividadeVinculada')),
                ('idProfessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Professor')),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 17, 12, 50, 311605)),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='DTSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 17, 12, 50, 311605)),
        ),
    ]
