# Generated by Django 2.0.3 on 2018-05-01 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0012_auto_20180501_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assunto', models.CharField(max_length=60)),
                ('Referencia', models.CharField(max_length=200)),
                ('Conteudo', models.TextField()),
                ('StatusMensagem', models.CharField(default='Entregue', max_length=10)),
                ('DTEnvio', models.DateTimeField(default=datetime.datetime(2018, 5, 1, 17, 22, 39, 841479))),
                ('DTResposta', models.DateTimeField(blank=True, null=True)),
                ('resposta', models.TextField()),
                ('idAluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Aluno')),
                ('idProfessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Professor')),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 17, 22, 39, 841479)),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='DtEntrega',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 17, 22, 39, 841479)),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='DTSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 17, 22, 39, 841479)),
        ),
    ]
