# Generated by Django 2.0.3 on 2018-05-02 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0014_auto_20180502_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 18, 57, 29, 671173)),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='DtEntrega',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 18, 57, 29, 686773)),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='DTEnvio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 18, 57, 29, 686773)),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='DTSolicitacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 18, 57, 29, 671173)),
        ),
    ]
