# Generated by Django 2.0.3 on 2018-05-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(default='Aberta', max_length=7)),
                ('planoDeEnsino', models.TextField()),
                ('cargaHoraria', models.SmallIntegerField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('ementa', models.TextField()),
                ('conteudoProgramatico', models.TextField()),
                ('bibliografiaBasica', models.TextField()),
                ('bibliografiaComplementas', models.TextField()),
                ('percentualPratico', models.SmallIntegerField()),
                ('percentualTeorico', models.SmallIntegerField()),
            ],
        ),
    ]
