# Generated by Django 2.0.3 on 2018-05-01 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='idCoordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
