# Generated by Django 2.0.3 on 2018-05-01 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0007_disciplinaofertada'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 16, 18, 40, 866866)),
        ),
    ]
